### ISSUE TITLE
ERR_MODULE_NOT_FOUND - Cannot find package

### ISSUE THREAD

**Issue by Ataraxy** [serverless/cloud#135] opened 2022-03-23 23:05 UTC
Example:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dayjs' imported from /tmp/task/index.js
    at new NodeError (node:internal/errors:371:5)
    at packageResolve (node:internal/modules/esm/resolve:932:9)
    at moduleResolve (node:internal/modules/esm/resolve:978:18)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at Ce (file:///opt/nodejs/cloud/loader.mjs:5:2103)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

All that exists within the index.js file is this:

```
import { api } from '@serverless/cloud'
import dayjs from 'dayjs'

api.get('/', async (_req, res) => {
  res.send(dayjs().format())
})
```

This is in a brand new app that was created with the js api template. Both the dayjs package is correctly installed and type module are in the package.json

Even importing properly exported modules from a local file provides a similar error instead of 'cannot find package' it would be 'cannot find module'.

I'm at a loss for why this is no longer working when it was just fine a few days ago.

**Comment by dougmoscrop** [comment] 2022-03-24 00:04
Are you on Windowa by any chance?

What version does cloud -v print?

**Comment by Ataraxy** [comment] 2022-03-24 00:17
Yes I am.

Using v2.8.1

**Comment by dougmoscrop** [comment] 2022-03-24 00:23
Okay, there was a bug with how we synced file paths that should be fixed, but I think you might need to edit a fille with the shell open, have you done that?  If so can you provide me your org name?

**Comment by Ataraxy** [comment] 2022-03-24 00:33
The org name is adinventive.

For what it's worth I've only been editing files with the cloud shell open.

**Comment by dougmoscrop** [comment] 2022-03-24 01:41
gotcha, working on it now, I think I know what the issue is, sorry about this.

**Comment by dougmoscrop** [comment] 2022-03-24 02:37
Hmm, no, honestly this is behaving as if you're running an older CLI.  You've exited and restarted it (like you don't have a long-running shell going, and then you're running 'cloud -v' in a separate terminal, or have a second shell running)

Can you uninstall/reinstall the cli globally - and also, try creating a new project, does it still happen?

**Comment by Ataraxy** [comment] 2022-03-24 02:47
I've done both with the same result.

**Comment by dougmoscrop** [comment] 2022-03-24 03:10
Okay, sorry about this.  I know it's annoying but let's start from squre one to make sure we are on the same page:

- run `npm uninstall -g @serverless/cloud`
- run `cloud` (confirm it errors that it cannot be found)
- mkdir some-new-dir
- cd some-new-dir
- run `npm install -g @serverless/cloud`
- run `cloud -v` (confirm it prints 2.8.1)
- run `cloud` and follow the prompts to create a new project, pick the API sample
- install dayjs and import it

let me know what happens at that point and what the name of the app is

**Comment by Ataraxy** [comment] 2022-03-24 03:14
It's all good. Those were precisely the steps I took a bit ago.

I just went through the entire process again.

The name of the app is error-example

**Comment by dougmoscrop** [comment] 2022-03-24 04:05
not my finest hour, I think I got it - can you try 2.8.2?

**Comment by Ataraxy** [comment] 2022-03-24 04:07
Looks like everything is working again on my end with the new version. 

I really appreciate the effort!

**Comment by dougmoscrop** [comment] 2022-03-24 04:11
Thank you for being so patient!

**Closed** 2022-03-24 17:20 UTC
